### ISSUE TITLE
DWCheckBoxView with multiSelect YES

### ISSUE THREAD

**Issue by thiagopac** [CodeWicky/DWCheckBox#1]
Please, can you provide an example of DWCheckBoxView with multiSelect YES and DWCheckBoxManager set up. With multiSelect YES, the multi checkbox is not setting correctly, only with multiSelect NO.

Thanks!

**Comment by CodeWicky** [comment]
Hi bro, I'm sorry for answering u so late.

I can't understand what do you mean by 

> With multiSelect YES, the multi checkbox is not setting correctly, only with multiSelect NO.

I use DWCheckBox in my own project with MultiSelectMode and it works.

I guess u r trying to build a DWCheckBoxManager yourself to fit your demand and these may help you:

> All you need to do in selectedChangeBlock is to change all cell's selectStatus.

So u may initial a manager like this:

```objectivec
DWCheckBoxDefaultLayout * layout = [DWCheckBoxDefaultLayout new];
    
    CustomCheckBoxCell * cell1 = [CustomCheckBoxCell buttonWithType:(UIButtonTypeCustom)];
    [cell1 setFrame:CGRectMake(0, 0, 44, 44)];
    CustomCheckBoxCell * cell2 = [CustomCheckBoxCell buttonWithType:(UIButtonTypeCustom)];
    [cell2 setFrame:CGRectMake(0, 0, 44, 44)];
    NSArray * cells = @[cell1,cell2];
    
    DWCheckBoxManager * manager = [[DWCheckBoxManager alloc] initWithCountOfBoxes:cells.count multiSelect:YES defaultSelect:@[@1] selectedChangeBlock:^(DWCheckBoxManager *mgr, id currentSelect, NSString *identifier) {
        NSArray * arr = currentSelect;
        [cells enumerateObjectsUsingBlock:^(id<DWCheckBoxCellProtocol> obj, NSUInteger idx, BOOL * _Nonnull stop) {
            if ([arr containsObject:@(idx)]) {
                [obj cellBeSelected:YES withImage:mgr.selectedImage];
            } else {
                [obj cellBeSelected:NO withImage:mgr.unSelectedImage];
            }
        }];
    }];
    
    DWCheckBoxView * view = [[DWCheckBoxView alloc] initWithFrame:CGRectMake(0, 64, 414, 672) layout:layout manager:manager multiSelect:YES cells:cells];
    [self.view addSubview:view];
```

Code above works on multiSelectMode.And I've update DWCheckBox to 1.1.0 which provide defaultManager.

Hope to help u.
